[package]
name = "render_gl_derive"
version = "0.1.0"
authors = ["arielalvarez <ariel.alvarez.android@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

[lib]
proc-macro = true